services:
  web:
    build: .

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    
    ports:
      - 8000:8000

  mongo:
    image: mongo:4.2
    
    ports: 
      - 27017:27017
      
    volumes:
      - ./datos_db:/data/db